name: "Example Actions"
branding:
  icon: "package"
  color: "red"
description: "Test Bed for random actions"
author: "MikeHamilton-RW"
inputs:
  GITHUB_TOKEN:
    description: "Github secret token to allow automated publishing of APK to release."
runs:
  using: "docker"
  image: "Dockerfile"
