name: "APK Publisher"
description: "Publish Release on Github"
author: "MikeHamilton-RW"
inputs:
  GITHUB_TOKEN:
    description: "Github secret token to allow automated publishing of artifacts to a release."
runs:
  using: "docker"
  image: "Dockerfile"
