name: "Release Publisher"
description: "Publish Release on Github"
author: "MikeHamilton-RW"
inputs:
  GITHUB_TOKEN:
    description: "Github secret token to allow automated publishing of artifacts to a release."
  GITHUB_REPOSITORY:
    description: "Utilize the github.repository environment variable"
  ARTIFACT_FOLDER:
    description: "Utilize steps.folder_name_output.outputs.folder_name environment variable"
  RELEASE_TITLE:
    description: "Utilize the steps.repo_name_output.outputs.repo_name environment variable"
  VERSION_NUMBER:
    description: "Utilize the steps.version_build_output.outputs.version_build environment variable"
  COMMIT_SHA:
    description: "Utilize the steps.commit_sha_step.outputs.commit_sha environment variable"
  SIGNER:
    description: "Utilize the steps.signed_aligned_artifact_output.outputs.release_artifact_signer environment variable"
runs:
  using: "docker"
  image: "Dockerfile"