name: Branch Build Test Lint

on:
  push:
    branches-ignore:
      - master
      - integration

jobs:
  BranchBuildAndTest:

    runs-on: ubuntu-latest

    steps:

    - name: Run the actions/checkout lib v1
      uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - name: Set gradle version to 6.0
      run: chmod +x gradlew && ./gradlew wrapper --gradle-version=6.0
    
    # TODO: Set version of minSdk, targetSdk, compileSdk here also? Override them preferrably so devs can do local build still.

    - name: Check gradle version
      run: ./gradlew --version

    - name: Build the Debug
      run: ./gradlew assembleDebug

    - name: Build the Release
      run: ./gradlew assembleRelease
    
    - name: Run Unit Tests on Debug
      run: ./gradlew testDebugUnitTest

    - name: Run Unit Tests on Release
      run: ./gradlew testReleaseUnitTest
      
    - name: Check directory
      run: pwd && cd sdk/build/outputs/aar/ && ls -l
    
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: WN-SDK_version # TODO: Capture version number, place in name of artifact. Will be able to use version for package creation also.
        path: sdk/build/outputs/aar

  BranchLint:

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Run the actions/checkout lib v1
      uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set gradle version
      run: chmod +x gradlew && ./gradlew wrapper --gradle-version=6.0

    - name: Check gradle version
      run: ./gradlew --version
      
    - name: Run lint
      run: ./gradlew lint
