name: Integration Pull Request

on:
  pull_request:
    branches:
      - integration

jobs:
  IntegrationPullRequestBuildAndTest:

    runs-on: ubuntu-latest
    env: 
      MAJOR_VERSION: 0
      MINOR_VERSION: 0
      PATCH_VERSION: 0

    steps:

    - name: Generate build number
      uses: einaregilsson/build-number@v2
      with:
        token: ${{secrets.github_token}}

    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"
    
# ERROR: Couldn't find an open pull request for branch with head at .
#     - name: Example PR comment 1
#       uses: unsplash/comment-on-pr@master
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         msg: "Check out this message! (unsplash/comment-on-pr@master)"
          
    - name: Example PR comment 2
      uses: thollander/actions-comment-pull-request@master
      with:
        message: 'Example of message! (thollander/actions-comment-pull-request@master)'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Example PR comment 3
      uses: mshick/add-pr-comment@v1
      with:
        message: |
          **Hello** (mshick/add-pr-comment@v1)
          🌏
          !
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-repeats: false
      
    - name: Run the actions/checkout lib v1
      uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Get application version
      run: echo "::set-env name=MAJOR_VERSION::$(cat build.gradle | grep 'majorVersion = ' | awk '{print $3}')" &&
        echo "::set-env name=MINOR_VERSION::$(cat build.gradle | grep 'minorVersion = ' | awk '{print $3}')" &&
        echo "::set-env name=PATCH_VERSION::$(cat build.gradle | grep 'patchVersion = ' | awk '{print $3}')"

    - name: Echo android application/library version
      run: echo "Application version v"$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION

    - name: Set gradle version
      run: chmod +x gradlew && ./gradlew wrapper --gradle-version=6.0

    - name: Check gradle version
      run: ./gradlew --version

    - name: Build the Debug
      run: ./gradlew assembleDebug

    - name: Build the Release
      run: ./gradlew assembleRelease

    - name: Run Unit Tests on Debug
      run: ./gradlew testDebugUnitTest

    - name: Run Unit Tests on Release
      run: ./gradlew testReleaseUnitTest

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: WN-SDK
        path: sdk/build/outputs/aar

  IntegrationPullRequestLint:

    runs-on: ubuntu-latest

    steps:

    - name: Run the actions/checkout lib v1
      uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set gradle version
      run: chmod +x gradlew && ./gradlew wrapper --gradle-version=6.0

    - name: Check gradle version
      run: ./gradlew --version

    - name: Run lint
      run: ./gradlew lint
