name: Master Branch Push Create Release

on:
  push:
    branches:
      - master

jobs:
  MasterPushCreateRelease:

    runs-on: ubuntu-latest

    steps:

    - name: Run the actions/checkout lib v1
      uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set gradle version
      run: chmod +x gradlew && ./gradlew wrapper --gradle-version=6.0

    - name: Check gradle version
      run: ./gradlew --version

    - name: Build the Release
      run: ./gradlew assembleRelease

    - name: Run Unit Tests on Release
      run: ./gradlew testReleaseUnitTest

    - name: Publish the binaries to the release
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'example-*'
